openapi: 3.0.0
info:
  title: Venue and Show API
  version: 1.0.0
paths:
  /api/shows:
    get:
      summary: Get a list of all shows
      responses:
        200:
          description: Successfully retrieved the list of shows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Show'
    post:
      summary: Add a new show
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowInput'
      responses:
        201:
          description: Successfully created a new show
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Show'
        400:
          description: Bad request due to invalid input data
  /api/shows/{id}:
    get:
      summary: Get details of a specific show by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successfully retrieved the show details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Show'
        404:
          description: Show not found
    put:
      summary: Update details of a specific show by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowInput'
      responses:
        201:
          description: Successfully updated the show details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Show'
        400:
          description: Bad request due to invalid input data
        404:
          description: Show not found
    delete:
      summary: Delete a specific show by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Successfully deleted the show
        404:
          description: Show not found
  /api/venues:
    get:
      summary: List all venues
      operationId: getVenues
      responses:
        '200':
          description: A list of venues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Venue'
    post:
      summary: Create a new venue
      operationId: createVenue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Venue'
      responses:
        '201':
          description: Venue created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
        '400':
          description: Invalid input
  /api/venues/{id}:
     get:
      summary: Get a venue by ID
      operationId: getVenueById
      parameters:
        - name: id
          in: path
          description: Venue ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Venue found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
        '404':
          description: Venue not found
    put:
      summary: Update a venue by ID
      operationId: updateVenueById
      parameters:
        - name: id
          in: path
          description: Venue ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Venue'
      responses:
        '201':
          description: Venue updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Venue'
        '400':
          description: Invalid input
        '404':
          description: Venue not found
    delete:
      summary: Delete a venue by ID
      operationId: deleteVenueById
      parameters:
        - name: id
          in: path
          description: Venue ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Venue deleted
        '404':
          description: Venue not found
components:
  schemas:
    Venue:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
        city:
          type: string
        capacity:
          type: integer
      required:
        - name
        - address
        - city
        - capacity
    Show:
      type: object
      properties:
        id:
          type: integer
          format: int64
        venue_id:
          type: integer
          format: int64
        name:
          type: string
        rating:
          type: number
          format: float
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        price:
          type: number
          format: float
        tags:
          type: string
      required:
        - venue_id
        - name
        - rating
        - start_time
        - end_time
        - price
        - tags